default: &default
  timeout: 5000
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: maciej

development:
  <<: *default
  database: mc_dev

test:
  <<: *default
  database: mc_test
